### PR TITLE
fix: allow nrql editor to accept new lines/tabs

### LINKED ISSUE #508: Formatted NRQL queries for Flow KPIs result in an error
## Description

Not sure if this is a bug or enhancement, and likely lower priority, but when adding or editing a Flow KPI NRQL query, if a user pastes a formatted NRQL statement (with returns/new lines/ or tabs for indentation) into Pathpoint and clicks "preview" the user is presented with an "Oops Something went wrong" error screen.

## Steps to Reproduce

1. Open Pathpoint app and click into a specific flow
2. Click the Edit icon to put the Pathpoint flow into edit mode
3. Either add a new Flow KPI or edit an exiting Flow KPI
4. Paste a NRQL query that has new lines/tabs/returns in it into the NRQL for the KPI and click the Preview button
5. Notice the error screen that displays

## Expected Behaviour

I would expect no error screen at a minimum.  If it isn't possible to have formatted queries in a Flow KPI NRQL, could the app automatically reformat the NRQL taking out any formatting characters?  Or maybe if not automatically reformatting, we could display a helpful error on the field itself helping the user ensure they take out any special formatting characters and then re-trying the preview button?  Some form validation essentially?

## Relevant Logs / Console output

Looks like I see a `3rd-app-b560a5a6.js:1 GraphQLError: Syntax Error: Unterminated string.` error in the console.

## Your Environment

Chrome v133 on MacOS 14.6.1

### PR DESCRIPTION
**Pull request by khpeet**
fixes #508

### CODE REVIEW

File: src/utils/nrql.js [hunk 1]
```diff
@@ -45,3 +45,10 @@ export const removeDateClauseFromNrql = (nrql, token) => {
     return nrql;
   }
 };
+
+export const sanitizeQuery = (nrql) => {
+  return nrql
+    .replace(/[\n\r\t]+/g, ' ')
+    .replace(/\s+/g, ' ')
+    .trim();
```
Comment (amit-y) [inline src/utils/nrql.js:53]: Not sure if queries need to be trimmed to run. If not, you should remove this, too.
