### PR TITLE
fix: enhanced signal tooltip

### LINKED ISSUE #362: Add signal tooltip to expose more helpful metadata
Add a tooltip that mimics the platform tooltip in the navigator view, to show additional useful information: entity type/account/(maybe entity guid?)

Tooltip should show up in the flow and in the signal selection.

### PR DESCRIPTION
**Pull request by khpeet**
fixes #362

### CODE REVIEW

File: src/constants/signals.js [hunk 1]
```diff
@@ -12,3 +12,19 @@ export const SIGNAL_EXPAND = {
...
 };
+
+export const ALERT_SEVERITY = {
+  CRITICAL: 'CRITICAL',
+  NOT_ALERTING: 'NOT_ALERTING',
+  NOT_CONFIGURED: 'NOT_CONFIGURED',
+  WARNING: 'WARNING',
+};
+
+export const SIGNAL_TOOLTIP = {
```
Comment (amit-y) [inline src/constants/signals.js:23]: This should be in `src/constants/ui-content.js` since it's actual content that shows up in the UI.

**Review by amit-y — APPROVED** [review]
👍
