### PR TITLE
fix: added switch to hide all signals in edit mode for a given flow

### LINKED ISSUE #397: In Edit Mode, add option to hide all signals
Edit mode can get very cluttered as all signals are expanded by default, which can make it very hard to see the overall structure at a glance. Add a hide signals option that will hide all signals and instead show a message that shows the number of signals that have been selected for that step. E.g. 10 signals added.

### PR DESCRIPTION
**Pull request by khpeet**
fixes #397

### CODE REVIEW

File: src/components/stages/index.js [hunk 1]
```diff
@@ -655,17 +656,28 @@ const Stages = forwardRef(
...
+                      <Button
+                        className="button-tertiary-border"
+                        variant={Button.VARIANT.TERTIARY}
+                        sizeType={Button.SIZE_TYPE.SMALL}
+                        iconType={
+                          Button.ICON_TYPE.INTERFACE__SIGN__PLUS__V_ALTERNATE
+                        }
+                        onClick={addStageHandler}
+                      >
+                        Add a stage
```
Comment (amit-y) [inline src/components/stages/index.js:669]: Just an extra, but could we move this to the ui-content constants, please?

**Review by amit-y — DISMISSED** [review]

**Review by amit-y — APPROVED** [review]
