### PR TITLE
fix: clear placeholder/default text on EditInPlace refs

### LINKED ISSUE #516: [Edit Mode] Clear placeholder text
This appears in multiple places - e.g. Stage Name, Step Name, KPI name, etc

It is annoying to have to delete default text before starting to type the value you want. There's no reason to keep the default text visible once the user has entered the field, and having to manually delete that text first makes it quite cumbersome and is poor UX.

### PR DESCRIPTION
**Pull request by khpeet**
fixes #516

### CODE REVIEW

File: src/components/edit-in-place/index.js [hunk 1]
```diff
@@ -26,15 +24,19 @@ const EditInPlace = forwardRef(
       []
     );
 
-    useEffect(() => setText(value), [value]);
+    useEffect(() => setText(value || defaultValue), [value]);
```
Comment (amit-y) [inline src/components/edit-in-place/index.js:27]: `defaultValue` needs to go in the dependencies array

File: src/components/edit-in-place/index.js [hunk 2]
```diff
@@ -26,15 +24,19 @@ const EditInPlace = forwardRef(
...
 
     const editHandler = useCallback(() => {
       setInputWidth(contentRef.current?.offsetWidth || 0);
       setIsEditing(true);
-    }, []);
+      if (text === defaultValue) {
+        setText('');
+      }
+    }, [text]);
```
Comment (amit-y) [inline src/components/edit-in-place/index.js:35]: `defaultValue` missing in dependencies array

File: src/components/edit-in-place/index.js [hunk 3]
```diff
@@ -26,15 +24,19 @@ const EditInPlace = forwardRef(
...
 
     const blurHandler = useCallback(() => {
-      setValue?.((text || '').replace(/[\s\u00A0]+/g, ' ').trim());
+      const trimmedText = (text || '').replace(/[\s\u00A0]+/g, ' ').trim();
+      setValue?.(trimmedText || defaultValue);
       setIsEditing(false);
     }, [text, setValue]);
```
Comment (amit-y) [inline src/components/edit-in-place/index.js:41]: You know what I'm going to say, already! :) `defaultValue` needs to be in dependencies array

**Review by amit-y — APPROVED** [review]
