### PR TITLE
fix: flow creation default account to flow list account picker

### LINKED ISSUE #416: Signal Selection - Account dropdown default
Default the account dropdown in the signal selection screen to be the same as the account used for the flow.

### PR DESCRIPTION
**Pull request by khpeet**
fixes #416

### CODE REVIEW

File: nerdlets/create-flow/blank.js [hunk 1]
```diff
@@ -1,46 +1,28 @@
...
   );
 
   useEffect(() => {
-    if (!selectedAccountId) setSelectedAccountId(accountId);
+    if (!selectedAccountId) {
+      let accountName = (accounts.find((acc) => acc.id === accountId) || {})
+        .name;
+      setSelectedAccountName(accountName);
+      setSelectedAccountId(accountId);
+    }
```
Comment (amit-y) [inline nerdlets/create-flow/blank.js:23]: Looks like you're using this in both `blank.js` and `import.js`. I'd move this to the index file, and just send account name down to these components.

File: nerdlets/create-flow/import.js [hunk 2]
```diff
@@ -12,12 +11,18 @@ const UPLOADED_FILE_MSG = 'Uploaded file successfully.';
...
   const [structureOnly, setStructureOnly] = useState(false);
 
   useEffect(() => {
-    if (!selectedAccountId) setSelectedAccountId(accountId);
+    if (!selectedAccountId) {
+      let accountName = (accounts.find((acc) => acc.id === accountId) || {})
+        .name;
+      setSelectedAccountName(accountName);
+      setSelectedAccountId(accountId);
+    }
```
Comment (amit-y) [inline nerdlets/create-flow/import.js:25]: See previous comment.

**Comment by khpeet** [comment]
@amit-y - should be fixed - let me know if all good

File: nerdlets/create-flow/index.js [hunk 3]
```diff
@@ -21,7 +21,8 @@ const CreateFlowNerdlet = () => {
   const [page, setPage] = useState('start');
   const [{ accountId }] = usePlatformState();
   const { user } = useFetchUser();
-  const { data: accounts = [] } = useAccountsQuery();
+  const { data: accounts } = useAccountsQuery();
+  const accountName = (accounts.find((acc) => acc.id === accountId) || {}).name;
```
Comment (amit-y) [inline nerdlets/create-flow/index.js:25]: This approach is not recommended in the newer versions of React. I'd recommend setting `accountName` using `useState`, and define a `useEffect` with `accounts` and `accountId` as dependencies. Set the `accountName` within that `useEffect`. That way `accountName` only gets set when `accounts` or `accountId` changes.

File: nerdlets/create-flow/blank.js [hunk 4]
```diff
@@ -1,45 +1,23 @@
...
-          });
-
-          return acc;
-        },
-        { items: [], selected: null }
-      ),
-    [accounts, selectedAccountId]
-  );
+    if (!selectedAccountName) setSelectedAccountName(accountName);
+  }, [accountId, selectedAccountId, selectedAccountName]);
```
Comment (amit-y) [inline nerdlets/create-flow/blank.js:20]: I should have mentioned this in my previous review, but you can remove this whole block. Just use the `accountName` that's being passed to the component as a prop.

File: nerdlets/create-flow/blank.js [hunk 5]
```diff
@@ -71,15 +49,16 @@ const BlankFlow = ({ accountId, accounts = [], onCreate, onCancel }) => {
...
-          label="Select your account"
-          items={accountsSelect.items}
-          onSelect={({ id }) => setSelectedAccountId(id)}
-        />
-      </div>
+      <InlineMessage
+        className="account-inline-message"
+        label={
+          <>
+            This flow will be created in <strong>{selectedAccountName}</strong>.
```
Comment (amit-y) [inline nerdlets/create-flow/blank.js:56]: Use the `accountName` prop instead of the `selectedAccountName` state variable.

File: nerdlets/create-flow/import.js [hunk 6]
```diff
@@ -142,17 +119,19 @@ const ImportFlow = ({ accountId, accounts = [], onCreate, onCancel }) => {
...
         </HeadingText>
       </div>
-
       <div className="import-form">
+        <InlineMessage
+          className="account-inline-message"
+          label={
+            <>
+              This flow will be created in{' '}
+              <strong>{selectedAccountName}</strong>. To change the account,
```
Comment (amit-y) [inline nerdlets/create-flow/import.js:128]: Use the `accountName` prop instead of the `selectedAccountName` state variable.

File: nerdlets/create-flow/import.js [hunk 7]
```diff
@@ -1,24 +1,25 @@
...
+  const [selectedAccountName, setSelectedAccountName] = useState();
   const [jsonStatusMsg, setJsonStatusMsg] = useState('');
   const [showDragging, setShowDragging] = useState(false);
   const [structureOnly, setStructureOnly] = useState(false);
 
   useEffect(() => {
     if (!selectedAccountId) setSelectedAccountId(accountId);
-  }, [accountId, selectedAccountId]);
+    if (!selectedAccountName) setSelectedAccountName(accountName);
+  }, [accountId, selectedAccountId, selectedAccountName]);
```
Comment (amit-y) [inline nerdlets/create-flow/import.js:22]: See previous comment - remove this block and use `accountName` from the passed props

File: nerdlets/create-flow/import.js [hunk 8]
```diff
@@ -1,24 +1,25 @@
...
 import { sanitizeKpis, sanitizeStages } from '../../src/utils';
 
 const fileReader = new FileReader();
 const UPLOADED_FILE_MSG = 'Uploaded file successfully.';
 
-const ImportFlow = ({ accountId, accounts = [], onCreate, onCancel }) => {
+const ImportFlow = ({ accountId, accountName, onCreate, onCancel }) => {
   const [jsonText, setJsonText] = useState('');
   const [selectedAccountId, setSelectedAccountId] = useState();
+  const [selectedAccountName, setSelectedAccountName] = useState();
```
Comment (amit-y) [inline nerdlets/create-flow/import.js:14]: Don;t need this  anymore.

File: nerdlets/create-flow/blank.js [hunk 9]
```diff
@@ -1,45 +1,23 @@
...
+import { Button, HeadingText, InlineMessage, TextField } from 'nr1';
 
 import { Select } from '../../src/components';
 import { REFRESH_INTERVALS } from '../../src/constants';
 
-const BlankFlow = ({ accountId, accounts = [], onCreate, onCancel }) => {
+const BlankFlow = ({ accountId, accountName, onCreate, onCancel }) => {
   const [flowName, setFlowName] = useState('');
   const [selectedAccountId, setSelectedAccountId] = useState();
+  const [selectedAccountName, setSelectedAccountName] = useState();
```
Comment (amit-y) [inline nerdlets/create-flow/blank.js:12]: Use the `accountName` prop instead of this state variable. This was only needed when we handled changing the account from within the component.
